apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: srinivas-gonepudi-dev
data:
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: srinivas-gonepudi-dev
  labels:
    app: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: 025066240744.dkr.ecr.us-east-1.amazonaws.com/openshift-images-repo:catalogue
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: catalogue
      imagePullSecrets:
        - name: aws-ecr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: srinivas-gonepudi-dev
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: catalogue
  namespace: srinivas-gonepudi-dev
spec:
  to:
    kind: Service
    name: catalogue
  port:
    targetPort: 8080
