---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: srinivas-gonepudi-dev
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:           
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb      
        project: roboshop
        tier: db
    spec:
      containers:
        - name: mongodb
          image: 025066240744.dkr.ecr.us-east-1.amazonaws.com/openshift-images-repo:mongodb
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
      imagePullSecrets:
        - name: aws-ecr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: srinivas-gonepudi-dev
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
