apiVersion: v1
kind: ConfigMap
metadata:
  name: web
  namespace: srinivas-gonepudi-dev
data:
  nginx.conf: |
    # your nginx.conf content goes here
    server {
      listen 80;
      location / {
        proxy_pass http://catalogue:8080;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: srinivas-gonepudi-dev
  labels:
    app: nginx-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: nginx-web
        image: 025066240744.dkr.ecr.us-east-1.amazonaws.com/openshift-images-repo:nginx-web
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
          - name: nginx-cache
            mountPath: /var/cache/nginx
      imagePullSecrets:
        - name: aws-ecr-secret
      volumes:
        - name: nginx-conf
          configMap:
            name: web
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-cache
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  namespace: srinivas-gonepudi-dev
spec:
  selector:
    app: nginx-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-web
  namespace: srinivas-gonepudi-dev
spec:
  to:
    kind: Service
    name: nginx-web
  port:
    targetPort: 80
